-- ================================================
-- Template generated from Template Explorer using:
-- Create Procedure (New Menu).SQL
--
-- Use the Specify Values for Template Parameters 
-- command (Ctrl-Shift-M) to fill in the parameter 
-- values below.
--
-- This block of comments will not be included in
-- the definition of the procedure.
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		LESLIE DAWSON
-- Create date: 4/20/2011
-- Description:	A11 STORED PROCEDURE
-- =============================================
ALTER PROCEDURE A11
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

--TURN OFF TABLE CONSTRAINTS FOR DELETION PURPOSES
ALTER TABLE FACT_TABLE DROP CONSTRAINT FK_PILOT
ALTER TABLE FACT_TABLE DROP CONSTRAINT FK_CUSTOMER
ALTER TABLE FACT_TABLE DROP CONSTRAINT FK_TIME
ALTER TABLE FACT_TABLE DROP CONSTRAINT FK_MODEL
ALTER TABLE CUSTOMER_DIM NOCHECK CONSTRAINT ALL
ALTER TABLE PILOT_DIM NOCHECK CONSTRAINT ALL
ALTER TABLE MODEL_DIM NOCHECK CONSTRAINT ALL
ALTER TABLE TIME_DIM NOCHECK CONSTRAINT ALL

--DELETE ALL INFORMATION FROM TABLES

TRUNCATE TABLE CUSTOMER_DIM
TRUNCATE TABLE PILOT_DIM
TRUNCATE TABLE MODEL_DIM
TRUNCATE TABLE TIME_DIM
TRUNCATE TABLE FACT_TABLE

--TURN ON CONSTRAINTS AGAIN FOR REPOPULATION
ALTER TABLE CUSTOMER_DIM CHECK CONSTRAINT ALL
ALTER TABLE PILOT_DIM CHECK CONSTRAINT ALL
ALTER TABLE MODEL_DIM CHECK CONSTRAINT ALL
ALTER TABLE TIME_DIM CHECK CONSTRAINT ALL
ALTER TABLE FACT_TABLE CHECK CONSTRAINT ALL
ALTER TABLE FACT_TABLE
ADD CONSTRAINT [FK_CUSTOMER] FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER_DIM,
	CONSTRAINT [FK_PILOT] FOREIGN KEY (PILOTID) REFERENCES PILOT_DIM,
	CONSTRAINT [FK_MODEL] FOREIGN KEY (MODELID) REFERENCES MODEL_DIM,
	CONSTRAINT [FK_TIME] FOREIGN KEY (TIMEID) REFERENCES TIME_DIM

--INSERT INFORMATION INTO DIMENSION TABLES
INSERT INTO CUSTOMER_DIM (CUS_CODE, CUS_LNAME, CUS_FNAME)
SELECT	CUS_CODE, CUS_LNAME, CUS_FNAME
FROM	CUSTOMER

INSERT INTO PILOT_DIM (EMP_NUM, EMP_TITLE, EMP_LNAME, PIL_LICENSE, PIL_RATINGS)
SELECT	E.EMP_NUM, E.EMP_TITLE, E.EMP_LNAME, P.PIL_LICENSE, P.PIL_RATINGS
FROM	PILOT P INNER JOIN EMPLOYEE E ON P.EMP_NUM = E.EMP_NUM

INSERT INTO MODEL_DIM (MOD_CODE, MOD_MANUFACTURER, MOD_NAME, MOD_SEATS, MOD_CHG_MILE)
SELECT	MOD_CODE, MOD_MANUFACTURER, MOD_NAME, MOD_SEATS, MOD_CHG_MILE
FROM	MODEL

INSERT INTO TIME_DIM (CHARTER_DATE, DAY_NUM, WEEK_NUM, MONTH_NUM, QUARTER_NUM, YEAR_NUM)
SELECT DISTINCT CHAR_DATE, DAY(CHAR_DATE), DATEPART(WEEK, CHAR_DATE), MONTH(CHAR_DATE),
				DATEPART(QUARTER, CHAR_DATE), YEAR(CHAR_DATE)
FROM CHARTER


--DELETE ALL DATA FROM STAGING TABLE
TRUNCATE TABLE STAGING

--INSERT TRANSACTION INFORMATION INTO STAGING TABLE
INSERT INTO STAGING (CUS_CODE, EMP_NUM, MOD_CODE, CHARTER_DATE, DISTANCE, 
			HOURS_FLOWN, FUEL_GALLONS, OIL_QTS, MOD_CHG_MILE)
SELECT	C.CUS_CODE, P.EMP_NUM, M.MOD_CODE, CH.CHAR_DATE, CH.CHAR_DISTANCE,
		CH.CHAR_HOURS_FLOWN, CH.CHAR_FUEL_GALLONS, CH.CHAR_OIL_QTS, M.MOD_CHG_MILE
FROM	PILOT P INNER JOIN EMPLOYEE E ON P.EMP_NUM = E.EMP_NUM
		INNER JOIN CREW CR ON E.EMP_NUM = CR.EMP_NUM
		INNER JOIN CHARTER CH ON CR.CHAR_TRIP = CH.CHAR_TRIP
		INNER JOIN CUSTOMER C ON CH.CUS_CODE = C.CUS_CODE
		INNER JOIN AIRCRAFT A ON CH.AC_NUMBER = A.AC_NUMBER
		INNER JOIN MODEL M ON A.MOD_CODE = M.MOD_CODE
		
--ASSIGNING DW KEYS TO STAGING TABLE
UPDATE STAGING
SET	 CUSTOMERID = C.CUSTOMERID
FROM STAGING S INNER JOIN CUSTOMER_DIM C ON S.CUS_CODE = C.CUS_CODE

UPDATE STAGING
SET  PILOTID = P.PILOTID
FROM STAGING S INNER JOIN PILOT_DIM P ON S.EMP_NUM = P.EMP_NUM

UPDATE STAGING
SET  MODELID = M.MODELID
FROM STAGING S INNER JOIN MODEL_DIM M ON S.MOD_CODE = M.MOD_CODE

UPDATE STAGING
SET TIMEID = T.TIMEID
FROM STAGING S INNER JOIN TIME_DIM T ON S.CHARTER_DATE = T.CHARTER_DATE

--POPULATE FACT TABLE FROM STAGING TABLE
INSERT INTO FACT_TABLE
SELECT	CUSTOMERID, PILOTID, MODELID, TIMEID, DISTANCE, HOURS_FLOWN, FUEL_GALLONS,
		OIL_QTS, (DISTANCE * MOD_CHG_MILE) AS [COST]
FROM	STAGING
		
END


EXEC A11

SELECT *
FROM CUSTOMER_DIM

SELECT *
FROM PILOT_DIM

SELECT *
FROM MODEL_DIM

SELECT *
FROM TIME_DIM

SELECT *
FROM FACT_TABLE

SELECT *
FROM STAGING