--LESLIE DAWSON
--CIS 310-01
--ASSIGNMENT 11
--DUE 4/29/2011

--A11A
--CREATE DIMENSION TABLES
USE CIS31007

CREATE TABLE CUSTOMER_DIM
(
CUSTOMERID INT IDENTITY(1,1) NOT NULL,
CUS_CODE INT NOT NULL,
CUS_LNAME VARCHAR(25),
CUS_FNAME VARCHAR(25)
)

CREATE TABLE PILOT_DIM
(
PILOTID INT IDENTITY(1,1) NOT NULL,
EMP_NUM INT NOT NULL,
EMP_TITLE VARCHAR(5),
EMP_LNAME VARCHAR(25),
PIL_LICENSE VARCHAR(5),
PIL_RATINGS VARCHAR(25)
)

CREATE TABLE MODEL_DIM
(
MODELID INT IDENTITY(1,1) NOT NULL,
MOD_CODE VARCHAR(10) NOT NULL,
MOD_MANUFACTURER VARCHAR(15),
MOD_NAME VARCHAR(25),
MOD_SEATS INT,
MOD_CHG_MILE REAL
)

CREATE TABLE TIME_DIM
(
TIMEID INT IDENTITY(1,1) NOT NULL,
CHARTER_DATE DATETIME,
DAY_NUM INT,
WEEK_NUM INT,
MONTH_NUM INT,
QUARTER_NUM INT,
YEAR_NUM INT
)

--ADDING CONSTRAINTS TO DIMENSION TABLES
ALTER TABLE PILOT_DIM
ADD CONSTRAINT [PK_PILOT_DIM] PRIMARY KEY (PILOTID)

ALTER TABLE CUSTOMER_DIM
ADD CONSTRAINT [PK_CUSTOMER_DIM] PRIMARY KEY (CUSTOMERID)

ALTER TABLE TIME_DIM
ADD CONSTRAINT [PK_TIME_DIM] PRIMARY KEY (TIMEID)

ALTER TABLE MODEL_DIM
ADD CONSTRAINT [PK_MODEL_DIM] PRIMARY KEY (MODELID)


--CREATE FACT TABLE
CREATE TABLE FACT_TABLE
(
CUSTOMERID		INT NOT NULL,
PILOTID			INT NOT NULL,
MODELID			INT NOT NULL,
TIMEID			INT NOT NULL,
DISTANCE		FLOAT,
HOURS_FLOWN		FLOAT,
FUEL_GALLONS	FLOAT,
OIL_QTS			FLOAT,
COST			REAL
)

--ADDING CONSTRAINTS TO FACT TABLE
ALTER TABLE FACT_TABLE
ADD CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER_DIM,
	CONSTRAINT FK_PILOT FOREIGN KEY (PILOTID) REFERENCES PILOT_DIM,
	CONSTRAINT FK_MODEL FOREIGN KEY (MODELID) REFERENCES MODEL_DIM,
	CONSTRAINT FK_TIME FOREIGN KEY (TIMEID) REFERENCES TIME_DIM

ALTER TABLE FACT_TABLE
ADD PRIMARY KEY (CUSTOMERID, PILOTID, MODELID, TIMEID)

--CREATE STAGING TABLE
CREATE TABLE STAGING
(
CUSTOMERID INT,
PILOTID INT,
MODELID INT,
TIMEID INT,
CUS_CODE INT,
EMP_NUM INT,
MOD_CODE VARCHAR(10),
CHARTER_DATE DATETIME,
DISTANCE FLOAT,
HOURS_FLOWN FLOAT,
FUEL_GALLONS FLOAT,
OIL_QTS	FLOAT,
MOD_CHG_MILE FLOAT
)

