--1
SELECT	CHAR_TRIP, CHAR_DATE, AC_NUMBER, CHAR_DESTINATION
FROM	CHARTER

--2
SELECT	CHAR_DATE, AC_NUMBER, CHAR_DESTINATION, CHAR_DISTANCE, CHAR_HOURS_FLOWN
FROM	CHARTER
WHERE	AC_NUMBER = '2778V'

--3
CREATE VIEW AC2778V AS
		SELECT	CHAR_DATE, AC_NUMBER, CHAR_DESTINATION, CHAR_DISTANCE, CHAR_HOURS_FLOWN
		FROM	CHARTER
		WHERE	AC_NUMBER = '2778V'

--4
SELECT	CH.CHAR_DATE, CH.AC_NUMBER, CH.CHAR_DESTINATION, C.CUS_LNAME, C.CUS_AREACODE, C.CUS_PHONE
FROM	CHARTER CH INNER JOIN CUSTOMER C ON CH.CUS_CODE = C.CUS_CODE
WHERE	CH.AC_NUMBER = '2778V'

--5
SELECT	CH.CHAR_DATE, CH.CHAR_DESTINATION, A.AC_NUMBER, M.MOD_NAME, M.MOD_CHG_MILE
FROM	INNER JOIN AIRCRAFT A ON CH.AC_NUMBER = A.AC_NUMBER
		INNER JOIN MODEL M ON A.MOD_CODE = M.MOD_CODE
WHERE	CH.CHAR_DATE = '02/06/06'

--6
SELECT	CH.CHAR_DATE, CH.CHAR_DESTINATION, A.AC_NUMBER, M.MOD_NAME, M.MOD_CHG_MILE, C.CUS_LNAME
FROM	CUSTOMER C INNER JOIN CHARTER CH ON C.CUS_CODE = CH.CUS_CODE
		INNER JOIN AIRCRAFT A ON CH.AC_NUMBER = A.AC_NUMBER
		INNER JOIN MODEL M ON A.MOD_CODE = M.MOD_CODE
WHERE	CH.CHAR_DATE >= '02/09/06'

--7
SELECT	CH.CHAR_DATE, CH.CHAR_DESTINATION, A.AC_NUMBER, M.MOD_CHG_MILE, CH.CHAR_DISTANCE,
		E.EMP_NUM, CR.CREW_JOB, E.EMP_LNAME
FROM	EMPLOYEE E INNER JOIN CREW CR ON E.EMP_NUM = CR.EMP_NUM
		INNER JOIN CHARTER CH ON CH.CHAR_TRIP = CR.CHAR_TRIP
		INNER JOIN AIRCRAFT A ON CH.AC_NUMBER = A.AC_NUMBER
		INNER JOIN MODEL M ON A.MOD_CODE = M.MOD_CODE
WHERE	CH.CHAR_DATE >= '02/09/06'

--8
SELECT	CH.CHAR_DATE, A.AC_NUMBER, M.MOD_NAME, CH.CHAR_HOURS_FLOWN, CH.CHAR_FUEL_GALLONS, 
		ROUND(CH.CHAR_FUEL_GALLONS/CH.CHAR_HOURS_FLOWN,2) AS [Gallons/Hour]
FROM	CHARTER CH INNER JOIN AIRCRAFT A ON CH.AC_NUMBER = A.AC_NUMBER
		INNER JOIN MODEL M ON A.MOD_CODE = M.MOD_CODE
WHERE	CH.CHAR_DATE >= '02/09/06'

--9
SELECT		CH.CHAR_DATE, C.CUS_LNAME, CH.CHAR_DISTANCE, M.MOD_CHG_MILE, ROUND((CH.CHAR_DISTANCE*M.MOD_CHG_MILE),2) AS [Mileage Charge]
FROM		CUSTOMER C INNER JOIN CHARTER CH ON C.CUS_CODE = CH.CUS_CODE
			INNER JOIN AIRCRAFT A ON CH.AC_NUMBER = A.AC_NUMBER
			INNER JOIN MODEL M ON A.MOD_CODE = M.MOD_CODE
WHERE		CH.CHAR_DATE >= '02/09/06'
ORDER BY	CH.CHAR_DATE, C.CUS_LNAME

--10
SELECT		CH.CHAR_DATE, C.CUS_LNAME, 
			ROUND((CH.CHAR_DISTANCE*M.MOD_CHG_MILE),2) AS [Mileage Charge],
			ROUND((CH.CHAR_HOURS_WAIT*50),2) AS [Waiting Charge],
			ROUND(((CH.CHAR_DISTANCE*M.MOD_CHG_MILE) + (CH.CHAR_HOURS_WAIT*50)),2) AS [Total Charge]
FROM		CUSTOMER C INNER JOIN CHARTER CH ON C.CUS_CODE = CH.CUS_CODE
			INNER JOIN AIRCRAFT A ON CH.AC_NUMBER = A.AC_NUMBER
			INNER JOIN MODEL M ON A.MOD_CODE = M.MOD_CODE
WHERE		CH.CHAR_DATE >= '02/09/06'
ORDER BY	CH.CHAR_DATE, C.CUS_LNAME

--11
SELECT		CUS_LNAME, CUS_FNAME, CUS_INITIAL, CUS_BALANCE
FROM		CUSTOMER
WHERE		CUS_BALANCE > 0
ORDER BY	CUS_BALANCE DESC

--12
SELECT	ROUND(AVG(CUS_BALANCE),2) AS [Average Balance], 
		ROUND(MIN(CUS_BALANCE),2) AS [Minimum Balance],
		ROUND(MAX(CUS_BALANCE),2) AS [Maximum Balance],
		ROUND(SUM(CUS_BALANCE),2) AS [Total Unpaid Bills]
FROM	CUSTOMER

--13
SELECT		AC_NUMBER, 
			COUNT(CHAR_TRIP) AS [Number of Trips],
			SUM(CHAR_DISTANCE) AS [Total Distance],
			ROUND(AVG(CHAR_DISTANCE),1) AS [Average Distance],
			ROUND(SUM(CHAR_HOURS_FLOWN),1) AS [Total Hours],
			ROUND(AVG(CHAR_HOURS_FLOWN),1) AS [Average Hours]
FROM		CHARTER
GROUP BY	AC_NUMBER

--14
SELECT	CH.CHAR_TRIP, CH.CHAR_DATE, A.AC_NUMBER, M.MOD_NAME, CH.CHAR_HOURS_FLOWN, E.EMP_LNAME, CR.CREW_JOB
FROM	EMPLOYEE E INNER JOIN CREW CR ON E.EMP_NUM = CR.EMP_NUM 
		INNER JOIN CHARTER CH ON CR.CHAR_TRIP = CH.CHAR_TRIP			
		INNER JOIN AIRCRAFT A ON CH.AC_NUMBER = A.AC_NUMBER
		INNER JOIN MODEL M ON A.MOD_CODE = M.MOD_CODE
WHERE	CH.CHAR_TRIP NOT IN
		(
		SELECT C.CHAR_TRIP
		FROM CREW C
		WHERE C.CREW_JOB = 'Copilot'
		)

--15
SELECT	EMP_NUM, EMP_LNAME, EMP_FNAME, 
		REPLACE(CONVERT(VARCHAR(9), EMP_HIRE_DATE, 6), ' ', '-') AS [EMP_HIRE_DATE], 
		REPLACE(CONVERT(VARCHAR(9), EMP_DOB, 6), ' ', '-') AS [EMP_DOB], 
		FLOOR(DATEDIFF(DD,EMP_DOB, GETDATE())/365.25) AS [Age],
		REPLACE(CONVERT(VARCHAR(9), GETDATE(), 6), ' ', '-') AS [Query Date]
FROM	EMPLOYEE
