use cis31000
--14
SELECT	COUNT(*)
FROM	CUSTOMER
WHERE	BALANCE < CREDIT_LIMIT

--15
SELECT	SUM(BALANCE)
FROM	CUSTOMER
WHERE	BALANCE < CREDIT_LIMIT AND
		REP_NUM = 20
		
--16
--INCORRECT An aggregate may not appear in the WHERE clause
SELECT	PART_NUM, DESCRIPTION, ON_HAND
FROM	PART
WHERE	ON_HAND > AVG(ON_HAND)

SELECT	PART_NUM, DESCRIPTION, ON_HAND
FROM	PART
WHERE	ON_HAND > (SELECT AVG(ON_HAND) FROM PART)

--17
SELECT	*
FROM	PART
WHERE	PRICE = (SELECT MIN(PRICE) FROM PART)

--COMMON MISTAKE
SELECT	PART_NUM, DESCRIPTION, PRICE, 
FROM	PART
WHERE	PRICE = MIN(PRICE)

--18
SELECT	*
FROM	PART
WHERE	PRICE = (SELECT MAX(PRICE) FROM PART)

--19
SELECT	COUNT(CUSTOMER_NUM)
FROM	CUSTOMER

--20
SELECT	REP_NUM, SUM(BALANCE) AS [TOTAL CUSTOMER BALANCE]
FROM	CUSTOMER
GROUP BY REP_NUM

--21
SELECT	CLASS, SUM(ON_HAND) AS [SEAN]
FROM	PART
WHERE	CLASS <> 'HW'
GROUP BY CLASS

--22
SELECT	*
FROM	PART
WHERE	DESCRIPTION IS NULL


