-- JAKE ELLIS
-- CIS310
-- A10

CREATE TABLE CUSTOMER_DIM
(
CUST_KEY	INT IDENTITY NOT NULL,
CUST_ID		INT,
NAME		VARCHAR(50),
BALANCE		FLOAT,
CREDIT_LIMIT	FLOAT,
REP_NUM		INT,
LOCATION_ID INT
)

ALTER TABLE CUSTOMER_DIM
ADD CONSTRAINT PK_CUSTOMER_DIM PRIMARY KEY (CUST_KEY)

CREATE TABLE REP_DIM
(
REP_KEY		INT IDENTITY NOT NULL,
REP_NUM		INT,
REP_LNAME	VARCHAR(15),
REP_FNAME	VARCHAR(15),
COMMISSION	FLOAT,
RATE		FLOAT,
LOCATION_ID INT
)

ALTER TABLE REP_DIM
ADD CONSTRAINT PK_REP_DIM PRIMARY KEY (REP_KEY)

CREATE TABLE PART_DIM
(
PART_KEY	INT IDENTITY NOT NULL,
PART_NUM	VARCHAR(20),
DESCRIPTION		VARCHAR(50),
ON_HAND		INT,
CLASS		VARCHAR(15),
PRICE		MONEY,
WAREHOUSE	INT
)

ALTER TABLE PART_DIM
ADD CONSTRAINT PK_PART_DIM PRIMARY KEY (PART_KEY)


CREATE TABLE TIME_DIM
(
TIME_KEY	INT IDENTITY NOT NULL,
DATE		DATETIME,
DAY			INT,
MONTH		INT,
YEAR		INT
)

ALTER TABLE TIME_DIM
ADD CONSTRAINT PK_TIME_DIM PRIMARY KEY (TIME_KEY)

CREATE TABLE FACT
(
CUST_KEY INT NOT NULL,
PART_KEY INT NOT NULL,
TIME_KEY INT NOT NULL,
REP_KEY INT NOT NULL,
TOTAL_QUANTITY INT,
PRICE MONEY,
)

CREATE TABLE LOCATION_DIM
(
LOCATION_ID INT NOT NULL IDENTITY,
STATE	VARCHAR(2),
CITY	VARCHAR(20),
ZIP		CHAR(5),
STREET	VARCHAR(30)
)

ALTER TABLE LOCATION_DIM
ADD CONSTRAINT PK_LOCATION_DIM PRIMARY KEY (LOCATION_ID)

ALTER TABLE FACT 
ADD CONSTRAINT PK_FACT PRIMARY KEY (CUST_KEY, PART_KEY, TIME_KEY,REP_KEY)

ALTER TABLE FACT
ADD CONSTRAINT FK_FACT_1 FOREIGN KEY (CUST_KEY) REFERENCES CUSTOMER_DIM

ALTER TABLE FACT
ADD CONSTRAINT FK_FACT_2 FOREIGN KEY (PART_KEY) REFERENCES PART_DIM

ALTER TABLE FACT
ADD CONSTRAINT FK_FACT_3 FOREIGN KEY (TIME_KEY) REFERENCES TIME_DIM

ALTER TABLE FACT
ADD CONSTRAINT FK_FACT_4 FOREIGN KEY (REP_KEY) REFERENCES REP_DIM

ALTER TABLE CUSTOMER_DIM
ADD CONSTRAINT FK_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION_DIM

ALTER TABLE REP_DIM
ADD CONSTRAINT FK_LOCATION_1 FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION_DIM


----------

CREATE TABLE STAGE
(
CUST_KEY	INT,
PART_KEY	INT,
TIME_KEY	INT,
REP_KEY		INT,
QUANTITY	INT,
PRICE		MONEY,
PART_NUM	VARCHAR(20),
REP_NUM		VARCHAR(20),
DATE	DATETIME,
CUST_ID		INT
)


INSERT INTO STAGE (PRICE, QUANTITY, PART_NUM, REP_NUM, DATE, CUST_ID)

SELECT OL.QUOTED_PRICE, OL.NUM_ORDERED, P.PART_NUM,
	 R.REP_NUM, O.ORDER_DATE, C.CUSTOMER_NUM
	 
FROM [REP-A10] R INNER JOIN [CUSTOMER-A10] C ON R.REP_NUM=C.REP_NUM
	INNER JOIN [ORDERS-A10] O ON C.CUSTOMER_NUM=O.CUSTOMER_NUM
	INNER JOIN [ORDER_LINE-A10] OL ON O.ORDER_NUM=OL.ORDER_NUM
	INNER JOIN [PART-A10] P ON P.PART_NUM=OL.PART_NUM

UPDATE STAGE
SET CUST_KEY = CUSTOMER_DIM.CUST_KEY
FROM STAGE INNER JOIN CUSTOMER_DIM ON STAGE.CUST_ID=CUSTOMER_DIM.CUST_ID

UPDATE STAGE
SET REP_KEY = REP_DIM.REP_KEY
FROM STAGE INNER JOIN REP_DIM ON STAGE.REP_NUM=REP_DIM.REP_NUM

UPDATE STAGE
SET PART_KEY = PART_DIM.PART_KEY
FROM STAGE INNER JOIN PART_DIM ON STAGE.PART_NUM=PART_DIM.PART_NUM

UPDATE STAGE
SET TIME_KEY = TIME_DIM.TIME_KEY
FROM STAGE INNER JOIN TIME_DIM ON STAGE.DATE=TIME_DIM.DATE

INSERT INTO FACT (CUST_KEY, PART_KEY, TIME_KEY, REP_KEY,TOTAL_QUANTITY,PRICE)
SELECT CUST_KEY, PART_KEY, TIME_KEY, REP_KEY, QUANTITY, PRICE
FROM STAGE

--------


					ALTER PROCEDURE A10

AS
BEGIN


ALTER TABLE FACT
DROP CONSTRAINT FK_FACT_1 

ALTER TABLE FACT
DROP CONSTRAINT FK_FACT_2 

ALTER TABLE FACT
DROP CONSTRAINT FK_FACT_3 

ALTER TABLE FACT
DROP CONSTRAINT FK_FACT_4 

ALTER TABLE CUSTOMER_DIM
DROP CONSTRAINT FK_LOCATION

ALTER TABLE REP_DIM
DROP CONSTRAINT FK_LOCATION_1


ALTER TABLE FACT NOCHECK CONSTRAINT ALL 

ALTER TABLE CUSTOMER_DIM NOCHECK CONSTRAINT ALL 

ALTER TABLE PART_DIM NOCHECK CONSTRAINT ALL

ALTER TABLE TIME_DIM NOCHECK CONSTRAINT ALL

ALTER TABLE REP_DIM NOCHECK CONSTRAINT ALL

ALTER TABLE LOCATION_DIM NOCHECK CONSTRAINT ALL

END
---------

BEGIN

TRUNCATE TABLE FACT
TRUNCATE TABLE CUSTOMER_DIM
TRUNCATE TABLE PART_DIM
TRUNCATE TABLE TIME_DIM
TRUNCATE TABLE REP_DIM
TRUNCATE TABLE LOCATION_DIM

END
------------

BEGIN

ALTER TABLE FACT CHECK CONSTRAINT ALL 

ALTER TABLE CUSTOMER_DIM CHECK CONSTRAINT ALL 

ALTER TABLE PART_DIM CHECK CONSTRAINT ALL

ALTER TABLE TIME_DIM CHECK CONSTRAINT ALL

ALTER TABLE REP_DIM CHECK CONSTRAINT ALL

ALTER TABLE LOCATION_DIM CHECK CONSTRAINT ALL

ALTER TABLE FACT
ADD CONSTRAINT FK_FACT_1 FOREIGN KEY (CUST_KEY) REFERENCES CUSTOMER_DIM

ALTER TABLE FACT
ADD CONSTRAINT FK_FACT_2 FOREIGN KEY (PART_KEY) REFERENCES PART_DIM

ALTER TABLE FACT
ADD CONSTRAINT FK_FACT_3 FOREIGN KEY (TIME_KEY) REFERENCES TIME_DIM

ALTER TABLE FACT
ADD CONSTRAINT FK_FACT_4 FOREIGN KEY (REP_KEY) REFERENCES REP_DIM

ALTER TABLE CUSTOMER_DIM
ADD CONSTRAINT FK_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION_DIM

ALTER TABLE REP_DIM
ADD CONSTRAINT FK_LOCATION_1 FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION_DIM


END
----------
BEGIN

INSERT INTO LOCATION_DIM

SELECT STATE,CITY,ZIP,STREET
FROM [CUSTOMER-A10]

	UNION

SELECT STATE,CITY,ZIP,STREET
FROM [REP-A10]


INSERT INTO REP_DIM (REP_NUM,REP_LNAME,REP_FNAME,COMMISSION, RATE, LOCATION_ID)
SELECT R.REP_NUM, R.LAST_NAME, R.FIRST_NAME,R.COMMISSION,R.RATE,L.LOCATION_ID
FROM LOCATION_DIM L INNER JOIN [REP-A10] R ON L.STATE=R.STATE
												AND L.CITY=R.CITY
												AND L.STREET=R.STREET
												AND L.ZIP=R.ZIP
												

INSERT INTO CUSTOMER_DIM (CUST_ID,NAME, BALANCE, CREDIT_LIMIT, REP_NUM, LOCATION_ID)
SELECT  C.CUSTOMER_NUM,C.CUSTOMER_NAME, C.BALANCE, C.CREDIT_LIMIT, C.REP_NUM, L.LOCATION_ID
FROM LOCATION_DIM L INNER JOIN [CUSTOMER-A10] C ON L.STATE=C.STATE 
												AND L.CITY=C.CITY
												AND L.STREET=C.STREET
												AND L.ZIP=C.ZIP

INSERT INTO  CUSTOMER_DIM (CUST_ID, NAME, BALANCE, CREDIT_LIMIT, REP_NUM)
SELECT C.CUSTOMER_NUM, C.CUSTOMER_NAME, C.BALANCE, C.CREDIT_LIMIT, C.REP_NUM
FROM [CUSTOMER-A10] C

INSERT INTO PART_DIM (PART_NUM, DESCRIPTION, ON_HAND, CLASS, PRICE, WAREHOUSE)
SELECT P.PART_NUM, P.DESCRIPTION, P.ON_HAND, P.CLASS, P.PRICE, P.WAREHOUSE
FROM [PART-A10] P

INSERT INTO  TIME_DIM (DATE, YEAR, MONTH, DAY)
SELECT ORDER_DATE, YEAR(ORDER_DATE), MONTH(ORDER_DATE), DAY(ORDER_DATE)
FROM [ORDERS-A10]

INSERT INTO  REP_DIM (REP_NUM, REP_LNAME, REP_FNAME, COMMISSION, RATE)
SELECT REP_NUM, LAST_NAME, FIRST_NAME, COMMISSION, RATE
FROM [REP-A10]

INSERT  INTO LOCATION_DIM (STATE,CITY,ZIP,STREET)
SELECT STATE,CITY,ZIP,STREET
FROM [CUSTOMER-A10]

END 
GO
-----

EXEC A10

--1. What is the average sale amount (quantity * quoted price) by customer in the last 3 months?

SELECT C.CUST_ID, C.NAME, AVG(F.TOTAL_QUANTITY*F.PRICE) AS "AVERAGE SALE AMOUNT"
FROM CUSTOMER_DIM C INNER JOIN FACT F ON C.CUST_KEY=F.CUST_KEY
	INNER JOIN TIME_DIM T ON F.TIME_KEY=T.TIME_KEY
WHERE MONTH IN (12,11,10) AND YEAR = (2011)
GROUP BY C.CUST_ID, C.NAME

--2. For parts that have been sold to more than one customer list description and quantity of sale by month.

SELECT COUNT(P.PART_NUM) AS "NUMBER ORDERED",P.DESCRIPTION, F.TOTAL_QUANTITY, T.MONTH
FROM FACT F INNER JOIN PART_DIM P ON F.PART_KEY=P.PART_KEY
			INNER JOIN TIME_DIM T ON F.TIME_KEY=T.TIME_KEY
GROUP BY P.DESCRIPTION, F.TOTAL_QUANTITY, T.MONTH
HAVING COUNT(P.PART_NUM) > 1
ORDER BY T.MONTH

--3. What is the total quantity of sale by rep in each city?
SELECT R.REP_NUM, R.REP_LNAME, R.REP_FNAME, L.CITY, SUM(F.TOTAL_QUANTITY) AS "TOTAL QUANTITY"
FROM REP_DIM R INNER JOIN FACT F ON R.REP_KEY = F.REP_KEY
		INNER JOIN LOCATION_DIM L ON L.LOCATION_ID=R.LOCATION_ID
GROUP BY R.REP_NUM, R.REP_LNAME, L.CITY, R.REP_FNAME
ORDER BY R.REP_NUM
