--- JAKE ELLIS
-- A9 #4
-- STORED PROCEDURE

ALTER PROCEDURE A9  
AS
----- #4-1  --------
	BEGIN 
	
DECLARE @EMP_TOTAL_HOURS FLOAT
UPDATE EMPLOYEE
SET EMP_TOTAL_HOURS = 0

	END
----- END #4-1 --------


------ #4-2 --------	
	BEGIN
	
DECLARE JME CURSOR FOR
SELECT EMP_NUM, SUM(ASSIGN_HOURS) AS "SUM"
FROM ASSIGNMENT
GROUP BY EMP_NUM

	DECLARE @SUM FLOAT
	DECLARE @EMP_NUM FLOAT
    
OPEN JME 
FETCH NEXT FROM JME INTO @EMP_NUM, @SUM
WHILE(@@FETCH_STATUS=0)
BEGIN
	PRINT(@EMP_NUM +''+ @SUM )
		UPDATE EMPLOYEE
		SET EMP_TOTAL_HOURS = @SUM
		WHERE EMP_NUM = @EMP_NUM
		FETCH NEXT FROM JME INTO @EMP_NUM, @SUM
    
    
    END
	CLOSE JME
	DEALLOCATE JME
END

---- END #4-2 -----


