-- JAKE ELLIS
--ASSIGNMENT 9

--#1

CREATE TABLE ASSIGNMENT( 
ASSIGN_NUM INT NOT NULL ,
ASSIGN_DATE SMALLDATETIME,
PROJ_NUM INT,
EMP_NUM INT,
ASSIGN_JOB INT,
ASSIGN_CHG_HR FLOAT,
ASSIGN_HOURS FLOAT,
ASSIGN_CHARGE FLOAT
)

		ALTER TABLE ASSIGNMENT 
		ADD CONSTRAINT PK_ASSIGNMENT PRIMARY KEY (ASSIGN_NUM)

		ALTER TABLE ASSIGNMENT 
		ADD CONSTRAINT FK_ASSIGNMENT FOREIGN KEY (EMP_NUM) REFERENCES EMPLOYEE

CREATE TABLE EMPLOYEE (
EMP_NUM INT NOT NULL,
EMP_LNAME VARCHAR(15),
EMP_FNAME VARCHAR (15),
EMP_INITIAL VARCHAR(1),
EMP_HIREDATE SMALLDATETIME,
JOB_CODE INT,
EMP_YEARS INT,
EMP_TOTAL_HOURS FLOAT
)

		ALTER TABLE EMPLOYEE 
		ADD CONSTRAINT PK_EMPLOYEE PRIMARY KEY(EMP_NUM)

		ALTER TABLE EMPLOYEE
		ADD CONSTRAINT FK_EMPLOYEE FOREIGN KEY (JOB_CODE) REFERENCES JOB

CREATE TABLE JOB (
JOB_CODE INT NOT NULL , 
JOB_DESRIPTION VARCHAR(30),
JOB_CHG_HOUR FLOAT,
JOB_LAST_UPDATE SMALLDATETIME,
)

		ALTER TABLE JOB
		ADD CONSTRAINT PK_JOB PRIMARY KEY(JOB_CODE)


CREATE TABLE PROJECT (
PROJ_NUM INT NOT NULL,
PROJ_NAME VARCHAR(20),
PROJ_VALUE FLOAT,
PROJ_BALANCE FLOAT,
EMP_NUM INT
)

		ALTER TABLE PROJECT
		ADD CONSTRAINT PK_PROJECT PRIMARY KEY (PROJ_NUM)

		ALTER TABLE PROJECT 
		ADD CONSTRAINT FK_PROJECT  FOREIGN KEY(EMP_NUM) REFERENCES EMPLOYEE

------------------

--- #3
INSERT INTO PROJECT
SELECT * FROM PROJECT1

INSERT INTO EMPLOYEE
SELECT * FROM  EMPLOYEE1

INSERT INTO ASSIGNMENT
SELECT * FROM ASSIGNMENT1

INSERT INTO JOB
SELECT * FROM JOB1

-- #6 --- TESTING

INSERT INTO ASSIGNMENT (ASSIGN_NUM, EMP_NUM, ASSIGN_HOURS)
VALUES (9998, 111, 80)

DELETE ASSIGNMENT
WHERE ASSIGN_NUM = 9998

UPDATE ASSIGNMENT
SET ASSIGN_HOURS = 100
WHERE ASSIGN_NUM = 9999

SELECT * FROM ASSIGNMENT
SELECT * FROM EMPLOYEE