-- ================================================
-- Template generated from Template Explorer using:
-- Create Trigger (New Menu).SQL
--
-- Use the Specify Values for Template Parameters 
-- command (Ctrl-Shift-M) to fill in the parameter 
-- values below.
--
-- See additional Create Trigger templates for more
-- examples of different Trigger statements.
--
-- This block of comments will not be included in
-- the definition of the function.
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Leslie Dawson
-- Create date: 4/13/2011
-- Description:	A8B - TRIGGER TO UPDATE CUS_TOTAL_DISTANCE IN CUSTOMER TABLE
--					  AFTER CHANGE MADE TO CHARTER TABLE
-- =============================================
ALTER TRIGGER A8B_TRIGGER_TO_UPDATE_CUS_TOTAL_DISTANCE
   ON  CHARTER 
   AFTER INSERT,DELETE,UPDATE
AS 
BEGIN
	DECLARE @CUS_CODE INT
	DECLARE	@DISTANCE_CHANGE REAL
	
	--FOR INSERT CASE (INSERTED TABLE NOT EMPTY)
	IF(EXISTS (SELECT * FROM INSERTED))
	BEGIN
			DECLARE	INSERT_CURSOR CURSOR FOR
			SELECT		I.CUS_CODE, SUM(I.CHAR_DISTANCE) AS [DISTANCE_CHANGE]
			FROM		INSERTED I
			GROUP BY	I.CUS_CODE
			
			OPEN INSERT_CURSOR
			FETCH NEXT FROM INSERT_CURSOR INTO @CUS_CODE, @DISTANCE_CHANGE
			WHILE(@@FETCH_STATUS = 0)
			BEGIN
					UPDATE	CUSTOMER
					SET		CUS_TOTAL_DISTANCE = CUS_TOTAL_DISTANCE + @DISTANCE_CHANGE
					WHERE	CUS_CODE = @CUS_CODE
					FETCH NEXT FROM INSERT_CURSOR INTO @CUS_CODE, @DISTANCE_CHANGE
			END
			CLOSE INSERT_CURSOR
			DEALLOCATE INSERT_CURSOR
	END

	--FOR DELETE CASE (DELETED TABLE NOT EMPTY)
	IF(EXISTS (SELECT * FROM DELETED))
	BEGIN
			DECLARE	DELETE_CURSOR CURSOR FOR
			SELECT		D.CUS_CODE, SUM(D.CHAR_DISTANCE) AS [DISTANCE_CHANGE]
			FROM		DELETED D
			GROUP BY	D.CUS_CODE
			
			OPEN DELETE_CURSOR
			FETCH NEXT FROM DELETE_CURSOR INTO @CUS_CODE, @DISTANCE_CHANGE
			WHILE(@@FETCH_STATUS = 0)
			BEGIN
					UPDATE	CUSTOMER
					SET		CUS_TOTAL_DISTANCE = CUS_TOTAL_DISTANCE - @DISTANCE_CHANGE
					WHERE	CUS_CODE = @CUS_CODE
					FETCH NEXT FROM DELETE_CURSOR INTO @CUS_CODE, @DISTANCE_CHANGE
			END
			CLOSE DELETE_CURSOR
			DEALLOCATE DELETE_CURSOR
	END
	
	--FOR UPDATE CASE (INSERTED AND DELETED TABLES NOT EMPTY)
	IF(EXISTS (SELECT * FROM DELETED) AND EXISTS (SELECT * FROM INSERTED))
	BEGIN
			DECLARE	UPDATE_CURSOR CURSOR FOR
			SELECT		I.CUS_CODE, SUM(I.CHAR_DISTANCE - D.CHAR_DISTANCE) AS [DISTANCE_CHANGE]
			FROM		INSERTED I INNER JOIN DELETED D ON I.CUS_CODE = D.CUS_CODE
			GROUP BY	I.CUS_CODE
			
			OPEN UPDATE_CURSOR
			FETCH NEXT FROM UPDATE_CURSOR INTO @CUS_CODE, @DISTANCE_CHANGE
			WHILE(@@FETCH_STATUS = 0)
			BEGIN
					UPDATE	CUSTOMER
					SET		CUS_TOTAL_DISTANCE = CUS_TOTAL_DISTANCE + @DISTANCE_CHANGE
					WHERE	CUS_CODE = @CUS_CODE
					FETCH NEXT FROM UPDATE_CURSOR INTO @CUS_CODE, @DISTANCE_CHANGE
			END
			CLOSE UPDATE_CURSOR
			DEALLOCATE UPDATE_CURSOR
	END
END

