USE CIS31032

CREATE TABLE PILOTDIM
(
	PILOTID INT IDENTITY(1,1) NOT NULL,
	EMP_NUM INT NOT NULL,
	EMP_TITLE NVARCHAR(4),
	EMP_LNAME NVARCHAR(15),
	PIL_LICENSE NVARCHAR(25),
	PIL_RATINGS NVARCHAR(25)
)

CREATE TABLE CUSTOMERDIM
(
	CUSTOMERID INT IDENTITY(1,1) NOT NULL,
	CUS_CODE INT NOT NULL,
	CUS_LNAME NVARCHAR(15),
	CUS_FNAME NVARCHAR(15)
)

CREATE TABLE TIMEDIM
(
	TIMEID INT IDENTITY(1,1) NOT NULL,
	CHARTER_DATE DATETIME,
	DAY_NUM INT,
	WEEK_NUM INT,
	MONTH_NUM INT,
	QUARTER_NUM INT,
	YEAR_NUM INT
)

CREATE TABLE MODELDIM
(
	MODELID INT IDENTITY(1,1) NOT NULL,
	MOD_CODE NVARCHAR(10) NOT NULL,
	MOD_MANUFACTURER NVARCHAR(10),
	MOD_NAME NVARCHAR(10),
	MOD_SEATS FLOAT,
	MOD_CHG_MILE REAL
)

CREATE TABLE FACT
(
	PILOTID INT NOT NULL,
	CUSTOMERID INT NOT NULL,
	TIMEID INT NOT NULL,
	MODELID INT NOT NULL,
	DISTANCE FLOAT,
	HOURS_FLOWN FLOAT,
	FUEL_GALLONS FLOAT,
	OIL_QTS FLOAT,
	COST REAL
)
	
ALTER TABLE PILOTDIM
ADD CONSTRAINT [PK_PILOTDIM] PRIMARY KEY (PILOTID)

ALTER TABLE CUSTOMERDIM
ADD CONSTRAINT [PK_CUSTOMERDIM] PRIMARY KEY (CUSTOMERID)

ALTER TABLE TIMEDIM
ADD CONSTRAINT [PK_TIMEDIM] PRIMARY KEY (TIMEID)

ALTER TABLE MODELDIM
ADD CONSTRAINT [PK_MODELDIM] PRIMARY KEY (MODELID)

ALTER TABLE FACT
ADD CONSTRAINT [FK_PILOT] FOREIGN KEY (PILOTID) REFERENCES PILOTDIM,
CONSTRAINT [FK_CUSTOMER] FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERDIM,
CONSTRAINT [FK_TIME] FOREIGN KEY (TIMEID) REFERENCES TIMEDIM,
CONSTRAINT [FK_MODEL] FOREIGN KEY (MODELID) REFERENCES MODELDIM

ALTER TABLE FACT
ADD PRIMARY KEY (PILOTID, CUSTOMERID, TIMEID, MODELID) 


SELECT *
FROM PILOTDIM

SELECT *
FROM CUSTOMERDIM

SELECT *
FROM TIMEDIM

SELECT *
FROM MODELDIM

SELECT *
FROM FACT

--CREATION OF STAGETABLE
CREATE TABLE STAGETABLE
(
	PILOTID INT,
	CUSTOMERID INT,
	MODELID INT,
	TIMEID INT,
	CHAR_DISTANCE FLOAT,
	CHAR_HOURS_FLOWN FLOAT,
	CHAR_FUEL_GALLONS FLOAT,
	CHAR_OIL_QTS FLOAT,
	MOD_CHG_MILE REAL,
	CUS_CODE INT,
	CHARTER_DATE DATETIME,
	MOD_CODE INT,
	EMP_NUM INT,
)

EXEC A11