-- Initialize LMC database

USE lmcdbase;

DROP TABLE IF EXISTS PERFORMANCEATTENDANCE;
DROP TABLE IF EXISTS REHEARSALATTENDANCE;
DROP TABLE IF EXISTS REHEARSAL;
DROP TABLE IF EXISTS PERFORMER;
DROP TABLE IF EXISTS ADSPACE;
DROP TABLE IF EXISTS ADVERTISER;
DROP TABLE IF EXISTS DONORCONTACT;
DROP TABLE IF EXISTS DONATION;
DROP TABLE IF EXISTS DONOR;
DROP TABLE IF EXISTS DOCUMENT;
DROP TABLE IF EXISTS SEASONTICKETPURCHASE;
DROP TABLE IF EXISTS SEASONTICKET;
DROP TABLE IF EXISTS SINGLEPERFORMANCETICKETPURCHASE;
DROP TABLE IF EXISTS SINGLEPERFORMANCETICKET;
DROP TABLE IF EXISTS PERFORMANCE;
DROP TABLE IF EXISTS CUSTOMERORDER;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS BOARDMEETINGATTENDANCE;
DROP TABLE IF EXISTS BOARDMEETING;
DROP TABLE IF EXISTS COMMITTEEMEMBER;
DROP TABLE IF EXISTS COMMITTEE;
DROP TABLE IF EXISTS BOARDMEMBER;
DROP TABLE IF EXISTS SYSTEMUSER;
DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON (
    PERSON_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PERSON_FIRSTNAME VARCHAR(15) NOT NULL,
    PERSON_MIDDLEINITIAL VARCHAR(1),
    PERSON_LASTNAME VARCHAR(15) NOT NULL,
    PERSON_HOMESTREETADDRESS1 VARCHAR(30),
    PERSON_HOMESTREETADDRESS2 VARCHAR(30),
    PERSON_HOMECITY VARCHAR(15),
    PERSON_HOMESTATE VARCHAR(2),
    PERSON_HOMEZIPCODE VARCHAR(10),
    PERSON_EMAILADDRESS VARCHAR(30),
    PERSON_HOMEPHONE VARCHAR(10),
    PERSON_WORKPHONE VARCHAR(10),
    PERSON_CELLPHONE VARCHAR(10),
    INDEX(PERSON_ID)
) ENGINE=INNODB;

CREATE TABLE SYSTEMUSER (
    SYSTEMUSER_ID INT NOT NULL PRIMARY KEY,
    SYSTEMUSER_USERID VARCHAR(10),
    SYSTEMUSER_PASSWORD VARCHAR(32),
    SYSTEMUSER_PERMISSIONLEVEL INT,
    FOREIGN KEY (SYSTEMUSER_ID) REFERENCES PERSON(PERSON_ID),
    INDEX(SYSTEMUSER_ID)
) ENGINE=INNODB;

CREATE TABLE BOARDMEMBER (
    BOARDMEMBER_ID INT NOT NULL PRIMARY KEY,
    BOARDMEMBER_WORKSTREETADDRESS1 VARCHAR(30),
    BOARDMEMBER_WORKSTREETADDRESS2 VARCHAR(30),
    BOARDMEMBER_WORKCITY VARCHAR(15),
    BOARDMEMBER_WORKSTATE VARCHAR(2),
    BOARDMEMBER_WORKZIPCODE VARCHAR(10),
    BOARDMEMBER_STARTDATE DATE,
    BOARDMEMBER_ROTATEOFFBOARDDATE DATE,
    BOARDMEMBER_OFFICER VARCHAR(20),
    INDEX(BOARDMEMBER_ID),
    FOREIGN KEY (BOARDMEMBER_ID) REFERENCES PERSON(PERSON_ID)
) ENGINE=INNODB;

CREATE TABLE COMMITTEE (
    COMMITTEE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    COMMITTEE_NAME VARCHAR(20),
    INDEX(COMMITTEE_ID)
) ENGINE=INNODB;

CREATE TABLE COMMITTEEMEMBER (
    BOARDMEMBER_ID INT NOT NULL,
    COMMITTEE_ID INT NOT NULL,
    PRIMARY KEY(BOARDMEMBER_ID, COMMITTEE_ID),
    INDEX(BOARDMEMBER_ID),
    INDEX(COMMITTEE_ID),
    FOREIGN KEY (BOARDMEMBER_ID) REFERENCES BOARDMEMBER(BOARDMEMBER_ID),
    FOREIGN KEY (COMMITTEE_ID) REFERENCES COMMITTEE(COMMITTEE_ID)
) ENGINE=INNODB;

CREATE TABLE BOARDMEETING (
    BOARDMEETING_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BOARDMEETING_DATE DATE,
    BOARDMEETING_NAME VARCHAR(20),
    BOARDMEETING_LOCATION VARCHAR(30),
    BOARDMEETING_COMMENT VARCHAR(1024),
    INDEX (BOARDMEETING_ID)
) ENGINE=INNODB;

CREATE TABLE BOARDMEETINGATTENDANCE (
    BOARDMEMBER_ID INT NOT NULL,
    BOARDMEETING_ID INT NOT NULL,
    BOARDMEETINGATTENDANCE_ATTENDED INT,
    BOARDMEETINGATTENDANCE_COMMENT VARCHAR(256),
    PRIMARY KEY(BOARDMEMBER_ID, BOARDMEETING_ID),
    INDEX(BOARDMEMBER_ID),
    INDEX(BOARDMEETING_ID),
    FOREIGN KEY (BOARDMEMBER_ID) REFERENCES BOARDMEMBER(BOARDMEMBER_ID),
    FOREIGN KEY (BOARDMEETING_ID) REFERENCES BOARDMEETING(BOARDMEETING_ID)
) ENGINE=INNODB;

CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT NOT NULL PRIMARY KEY,
    INDEX(CUSTOMER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES PERSON(PERSON_ID)
) ENGINE=INNODB;

CREATE TABLE CUSTOMERORDER (
    CUSTOMERORDER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERORDER_NUMBER INT,
    CUSTOMER_ID INT NOT NULL,
    INDEX(CUSTOMER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
) ENGINE=INNODB;

CREATE TABLE PERFORMANCE (
    PERFORMANCE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PERFORMANCE_DATE DATE,
    PERFORMANCE_TIME TIME,
    PERFORMANCE_NAME VARCHAR(20),
    PERFORMANCE_LOCATION VARCHAR(30),
    PERFORMANCE_COMMENT VARCHAR(1024),
    INDEX(PERFORMANCE_ID)
) ENGINE=INNODB;

CREATE TABLE SINGLEPERFORMANCETICKET (
    SINGLEPERFORMANCETICKET_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PERFORMANCE_ID INT NOT NULL,
    SINGLEPERFORMANCETICKET_NUMBERREMAINING INT,
    SINGLEPERFORMANCETICKET_PRICE DECIMAL(5, 2),
    INDEX(PERFORMANCE_ID),
    FOREIGN KEY (PERFORMANCE_ID) REFERENCES PERFORMANCE(PERFORMANCE_ID)
) ENGINE=INNODB;

CREATE TABLE SINGLEPERFORMANCETICKETPURCHASE (
    CUSTOMERORDER_ID INT NOT NULL,
    SINGLEPERFORMANCETICKET_ID INT NOT NULL,
    SINGLEPERFORMANCETICKETPURCHASE_QUANTITY INT,
    PRIMARY KEY(CUSTOMERORDER_ID, SINGLEPERFORMANCETICKET_ID),
    INDEX(CUSTOMERORDER_ID),
    INDEX(SINGLEPERFORMANCETICKET_ID),
    FOREIGN KEY (CUSTOMERORDER_ID) REFERENCES CUSTOMERORDER(CUSTOMERORDER_ID),
    FOREIGN KEY (SINGLEPERFORMANCETICKET_ID) REFERENCES SINGLEPERFORMANCETICKET(SINGLEPERFORMANCETICKET_ID)
) ENGINE=INNODB;

CREATE TABLE SEASONTICKET (
    SEASONTICKET_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SEASONTICKET_YEAR INT,
    SEASONTICKET_NUMBERREMAINING INT,
    SEASONTICKET_PRICE DECIMAL(5,2),
    INDEX(SEASONTICKET_ID)
) ENGINE=INNODB;

CREATE TABLE SEASONTICKETPURCHASE (
    CUSTOMERORDER_ID INT NOT NULL,
    SEASONTICKET_ID INT NOT NULL,
    SEASONTICKETPURCHASE_QUANTITY INT,
    INDEX(CUSTOMERORDER_ID),
    INDEX(SEASONTICKET_ID),
    FOREIGN KEY (CUSTOMERORDER_ID) REFERENCES CUSTOMERORDER(CUSTOMERORDER_ID),
    FOREIGN KEY (SEASONTICKET_ID) REFERENCES SEASONTICKET(SEASONTICKET_ID)
) ENGINE=INNODB;

CREATE TABLE DOCUMENT (
    DOCUMENT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DOCUMENT_NAME VARCHAR(20),
    DOCUMENT_LOCATION VARCHAR(256)
) ENGINE=INNODB;

CREATE TABLE DONOR (
    DONOR_ID INT NOT NULL,
    INDEX(DONOR_ID),
    FOREIGN KEY (DONOR_ID) REFERENCES PERSON(PERSON_ID)
) ENGINE=INNODB;

CREATE TABLE DONATION (
    DONATION_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DONATION_DATE DATE,
    DONATION_AMOUNT DECIMAL(8,2),
    DONATION_COMMENT VARCHAR(256),
    DONOR_ID INT NOT NULL,
    INDEX(DONOR_ID),
    FOREIGN KEY (DONOR_ID) REFERENCES DONOR(DONOR_ID)
) ENGINE=INNODB;

CREATE TABLE DONORCONTACT (
    DONORCONTACT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DONORCONTACT_DATE DATE,
    DONORCONTACT_COMMENT VARCHAR(256),
    DONOR_ID INT NOT NULL,
    CONTACTEDBY_ID INT NOT NULL,
    INDEX(DONOR_ID),
    INDEX(CONTACTEDBY_ID),
    FOREIGN KEY (DONOR_ID) REFERENCES DONOR(DONOR_ID),
    FOREIGN KEY (CONTACTEDBY_ID) REFERENCES PERSON(PERSON_ID)
) ENGINE=INNODB;

CREATE TABLE ADVERTISER (
    ADVERTISER_ID INT NOT NULL,
    ADVERTISER_BUSINESSNAME VARCHAR(30),
    INDEX(ADVERTISER_ID),
    FOREIGN KEY (ADVERTISER_ID) REFERENCES PERSON(PERSON_ID)
) ENGINE=INNODB;

CREATE TABLE ADSPACE (
    ADSPACE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ADVERTISER_ID INT NOT NULL,
    PERFORMANCE_ID INT NOT NULL,
    ADSPACE_SIZE VARCHAR(20),
    ADSPACE_PLACEMENT INT,
    ADSPACE_PRICE DECIMAL(5, 2),
    INDEX(ADVERTISER_ID),
    INDEX(PERFORMANCE_ID),
    FOREIGN KEY (ADVERTISER_ID) REFERENCES ADVERTISER(ADVERTISER_ID),
    FOREIGN KEY (PERFORMANCE_ID) REFERENCES PERFORMANCE(PERFORMANCE_ID)
) ENGINE=INNODB;

CREATE TABLE PERFORMER (
    PERFORMER_ID INT NOT NULL PRIMARY KEY,
    PERFORMER_SECTION VARCHAR(10),
    PERFORMER_SECTIONLEADER TINYINT(1),
    INDEX(PERFORMER_ID),
    FOREIGN KEY (PERFORMER_ID) REFERENCES PERSON(PERSON_ID)
) ENGINE=INNODB;

CREATE TABLE REHEARSAL (
    REHEARSAL_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    REHEARSAL_DATE DATE,
    REHEARSAL_LOCATION VARCHAR(30),
    REHEARSAL_COMMENT VARCHAR(1024),
    REHEARSAL_NAME VARCHAR(20),
    INDEX(REHEARSAL_ID)
) ENGINE=INNODB;

CREATE TABLE REHEARSALATTENDANCE (
    PERFORMER_ID INT NOT NULL,
    REHEARSAL_ID INT NOT NULL,
    REHEARSALATTENDANCE_ATTENDED INT,
    REHEARSALATTENDANCE_COMMENT VARCHAR(256),
    PRIMARY KEY(PERFORMER_ID, REHEARSAL_ID),
    INDEX(PERFORMER_ID),
    INDEX(REHEARSAL_ID),
    FOREIGN KEY (PERFORMER_ID) REFERENCES PERFORMER(PERFORMER_ID),
    FOREIGN KEY (REHEARSAL_ID) REFERENCES REHEARSAL(REHEARSAL_ID)
) ENGINE=INNODB;

CREATE TABLE PERFORMANCEATTENDANCE (
    PERFORMANCE_ID INT NOT NULL,
    PERFORMER_ID INT NOT NULL,
    PERFORMANCEATTENDANCE_ATTENDED INT,
    PERFORMANCEATTENDANCE_COMMENT VARCHAR(256),
    PRIMARY KEY(PERFORMANCE_ID, PERFORMER_ID),
    INDEX(PERFORMANCE_ID),
    INDEX(PERFORMER_ID),
    FOREIGN KEY (PERFORMANCE_ID) REFERENCES PERFORMANCE(PERFORMANCE_ID),
    FOREIGN KEY (PERFORMER_ID) REFERENCES PERFORMER(PERFORMER_ID)
) ENGINE=INNODB;

-- Leave the next two INSERTs to seed the SYSTEMUSER table. An LMC administrator will use this to log
-- in for the first time and set up their profile in PERSON and SYSTEMUSER and then delete the ADMIN 
-- ADMIN user from PERSON and SYSTEMUSER
INSERT INTO PERSON(PERSON_FIRSTNAME, PERSON_LASTNAME) VALUES('Test', 'Administrator');

INSERT INTO SYSTEMUSER 
    VALUES((SELECT PERSON_ID FROM PERSON WHERE PERSON_FIRSTNAME='Test'),
        'admin', MD5('@123!ADMIN^5AS'), 0);

